/* Replace with your SQL commands */
ALTER TABLE `student_temp` 
ADD COLUMN `place_of_birth` VARCHAR(255) NULL DEFAULT NULL AFTER `generate`,
ADD COLUMN `date_of_birth` DATE NULL DEFAULT NULL AFTER `place_of_birth`,
ADD COLUMN `gender` ENUM('MAN', 'WOMAN') NULL DEFAULT 'MAN' AFTER `date_of_birth`,
ADD COLUMN `religion` INT(11) NULL DEFAULT NULL AFTER `gender`,
ADD COLUMN `identity_id` INT(11) NULL DEFAULT NULL AFTER `religion`,
ADD COLUMN `identity_type_id` INT(11) NULL DEFAULT NULL AFTER `identity_id`,
ADD COLUMN `entry_semester` ENUM('1', '2') NOT NULL DEFAULT '1' AFTER `identity_type_id`,
ADD COLUMN `entry_status` ENUM('NEW', 'TRANSFER') NOT NULL DEFAULT 'NEW' AFTER `entry_semester`,
ADD COLUMN `status` INT(11) NOT NULL DEFAULT '1' AFTER `entry_status`,
ADD COLUMN `mother_name` VARCHAR(100) NULL DEFAULT NULL AFTER `status`,
ADD COLUMN `father_name` VARCHAR(100) NULL DEFAULT NULL AFTER `mother_name`,
ADD COLUMN `father_income` INT(11) NULL DEFAULT NULL AFTER `father_name`,
ADD COLUMN `mother_income` INT(11) NULL DEFAULT NULL AFTER `father_income`,
ADD COLUMN `school_name` VARCHAR(50) NULL DEFAULT NULL AFTER `mother_income`,
ADD COLUMN `school_telp` VARCHAR(12) NULL DEFAULT NULL AFTER `school_name`,
ADD COLUMN `school_address` VARCHAR(45) NULL DEFAULT NULL AFTER `school_telp`,
ADD COLUMN `school_departement` VARCHAR(80) NULL DEFAULT NULL AFTER `school_address`,
ADD COLUMN `school_end` INT(4) NULL DEFAULT NULL AFTER `school_departement`,
ADD COLUMN `institution_name` VARCHAR(50) NULL DEFAULT NULL AFTER `school_end`,
ADD COLUMN `institution_telp` VARCHAR(12) NULL DEFAULT NULL AFTER `institution_name`,
ADD COLUMN `institution_address` VARCHAR(45) NULL DEFAULT NULL AFTER `institution_telp`,
ADD COLUMN `institution_start` INT(4) NULL DEFAULT NULL AFTER `institution_address`,
ADD COLUMN `institution_end` INT(4) NULL DEFAULT NULL AFTER `institution_start`,
ADD COLUMN `semester_active` INT(11) NULL DEFAULT NULL AFTER `institution_end`,
ADD COLUMN `campus_name` VARCHAR(50) NULL DEFAULT NULL AFTER `semester_active`,
ADD COLUMN `campus_telp` VARCHAR(12) NULL DEFAULT NULL AFTER `campus_name`,
ADD COLUMN `campus_address` VARCHAR(45) NULL DEFAULT NULL AFTER `campus_telp`,
ADD COLUMN `campus_departement` VARCHAR(80) NULL DEFAULT NULL AFTER `campus_address`,
ADD COLUMN `campus_end` INT(4) NULL DEFAULT NULL AFTER `campus_departement`;
